### ISSUE TITLE
Software caused connection abort: socket write error

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-sync-common#14]
Originally posted as https://github.com/GooBox/goobox-sync-sia/issues/49.

Sometimes, java.net.SocketException is thrown:

```
2018-02-15 23:41:02 [pool-1-thread-4] ERROR c.l.n.control.win.MessageProcessor - Software caused connection abort: socket write error
java.net.SocketException: Software caused connection abort: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
    at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
    at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
    at com.liferay.nativity.control.win.MessageProcessor._handle(MessageProcessor.java:110)
    at com.liferay.nativity.control.win.MessageProcessor.run(MessageProcessor.java:70)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by jkawamoto** [comment]
Looking at the source code of com.liferay.nativity.control.win.MessageProcessor
https://github.com/liferay/liferay-nativity/blob/59f551e07e9601960bbb022f5ff8ec364bdbd79c/java/src/com/liferay/nativity/control/win/MessageProcessor.java#L110

This error seems failing to close a stream because it's already closed, and we hence can ignore it. @kaloyan-raev, what do you think about this?

**Comment by kaloyan-raev** [comment]
Yes, I think you are right. We can ignore this error.

**Comment by jkawamoto** [comment]
Good. I'll close this issue.
